### ISSUE TITLE
not working on macos

### ISSUE THREAD

**Issue by claudiug** [LaurentTreguier/autocomplete-dcd#5] opened 2016-07-15 19:43 UTC
Hello,

I try to use your package but no autocomplete.
using:
os x 10.11.4 (15E65)
atom latest
you package latest

`ps aux | grep dcd-server                                                                                                                                                     1 ↵
claudiug         1947   0.0  0.8  2532636  66504   ??  S     9:27PM   0:02.48 /usr/local/bin/dcd-server -I/Users/claudiug/work/ecr2/dlang-admin/source -I/Users/claudiug/work/ecr2/dlang-admin/src -I/Users/claudiug/.dub/packages/asdf-0.0.9/asdf/source/ -I/Users/claudiug/.dub/packages/dcd-0.8.0/src/ -I/Users/claudiug/.dub/packages/ddb-0.2.4/ddb/source/ -I/Users/claudiug/.dub/packages/derelict-ft-1.1.2/source/ -I/Users/claudiug/.dub/packages/derelict-gl3-1.0.18/source/ -I/Users/claudiug/.dub/packages/derelict-sdl2-2.0.0/source/ -I/Users/claudiug/.dub/packages/derelict-util-2.0.6/source/ -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/3rdparty -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/helloworld/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/helloworld/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/dmledit/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/dmledit/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/d3d/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/d3d/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/dminer/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/dminer/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/tetris/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/tetris/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/opengl/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/opengl/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/ircclient/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/ircclient/src -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/spreadsheet/source -I/Users/claudiug/.dub/packages/dlangui-0.8.30/dlangui/examples/spreadsheet/src -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsfml-2.1.1/src/ -I/Users/claudiug/.dub/packages/dsymbol-0.2.0-alpha7/src/ -I/Users/claudiug/.dub/packages/dub-0.9.25/source/ -I/Users/claudiug/.dub/packages/dunit-1.0.12/source/ -I/Users/claudiug/.dub/packages/dyaml-0.5.3/dyaml/source/ -I/Users/claudiug/.dub/packages/emsi_containers-0.4.3/src/ -I/Users/claudiug/.dub/packages/experimental_allocator-2.70.0-b1/src -I/Users/claudiug/.dub/packages/libasync-0.7.9/source/ -I/Users/claudiug/.dub/packages/libdparse-0.7.0-alpha9/src/ -I/Users/claudiug/.dub/packages/libev-5.0.0_4.04/./deimos -I/Users/claudiug/.dub/packages/libevent-2.0.1_2.0.16/source -I/Users/claudiug/.dub/packages/libevent-2.0.1_2.0.16/src -I/Users/claudiug/.dub/packages/memutils-0.4.6/memutils/source/ -I/Users/claudiug/.dub/packages/msgpack-d-1.0.0-beta.3/src/ -I/Users/claudiug/.dub/packages/openssl-1.1.4_1.0.1g/source -I/Users/claudiug/.dub/packages/openssl-1.1.4_1.0.1g/src -I/Users/claudiug/.dub/packages/painlessjson-1.3.7/source/ -I/Users/claudiug/.dub/packages/painlesstraits-0.2.0/source/ -I/Users/claudiug/.dub/packages/tinyendian-0.1.2/tinyendian/source/ -I/Users/claudiug/.dub/packages/x11-1.0.14/source/
claudiug          746   0.0  1.5  2602428 122904   ??  S     9:09PM   0:02.77 /usr/local/bin/dcd-server -I/Library/D/dmd/src/phobos/ -I/Library/D/dmd/src/druntime/import/ -I/Users/claudiug/.dub/packages/vibe-d-0.7.28/source -I/Users/claudiug/.dub/packages/asdf-0.0.8/asdf/source -I/Users/claudiug/.dub/packages/ddb-0.2.4/ddb/source -p9166
claudiug         2150   0.0  0.0  2423376    208 s001  R+    9:42PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn dcd-server`

I have no autocomplete.

Also, using sublime, and the autocomplete works fine.  And I love atom more :)

**Comment by LaurentTreguier** [comment] 2016-07-15 19:50
I don't have a mac, so this is going to be hard to debug... How long have you waited for completions ? Sometimes it can take a long time for DCD to start because of all the packages imported.

**Comment by claudiug** [comment] 2016-07-15 19:57
@LaurentTreguier thx for the quick reply. I wait for one minute. 
I have the same config on sublime and is very fast. 
If you tell me where to have a look, I will try to give you more details

**Comment by LaurentTreguier** [comment] 2016-07-15 20:03
What happens if you launch `dcd-server` manually ? It will only be able to complete the standard library, but if it works, then the problem would come from an imported dub package

**Comment by claudiug** [comment] 2016-07-15 20:08
this is what I get in stdout
`2016-07-15T22:07:35.530:server.d:main:190 0 symbols cached.
2016-07-15T22:07:35.530:server.d:main:191 Startup completed in 0.400539 milliseconds.
2016-07-15T22:07:41.202:server.d:main:283 Getting completions
2016-07-15T22:07:41.202:server.d:main:321 Request processed in 0.169124 milliseconds
2016-07-15T22:07:42.329:server.d:main:283 Getting completions
2016-07-15T22:07:42.329:first.d:visit:304 Could not locate object.d or object.di
2016-07-15T22:07:42.329:first.d:visit:382 Could not resolve location of module 'std/stdio'
2016-07-15T22:07:42.329:server.d:main:321 Request processed in 0.578096 milliseconds
2016-07-15T22:07:42.456:server.d:main:283 Getting completions
`

**Comment by LaurentTreguier** [comment] 2016-07-15 20:10
It looks fine... After launching it manually, do you get completions in Atom ?

**Comment by claudiug** [comment] 2016-07-15 20:11
nothing :(

**Comment by LaurentTreguier** [comment] 2016-07-15 20:25
Have you tried to get completions for strictly standard library functions or classes ? Is there any error in Atom's console ?

**Comment by claudiug** [comment] 2016-07-15 20:26
I will have a look now, 
do you load all the .dub packages by default?

**Comment by LaurentTreguier** [comment] 2016-07-15 20:27
Yes, it loads all dub packages by default. Which was a bad design decision, some packages such as tango even crash dcd-server at startup...

**Comment by claudiug** [comment] 2016-07-15 20:30
<img width="1280" alt="screen shot 2016-07-15 at 10 29 58 pm" src="https://cloud.githubusercontent.com/assets/969118/16887647/b0c07fd8-4adb-11e6-83f9-b48ae0f9ad91.png">

**Comment by claudiug** [comment] 2016-07-15 20:32
as you can see in image, nothing in atom network, like no message sent ...

**Comment by LaurentTreguier** [comment] 2016-07-15 20:32
What's in the 'console' tab ? It looks like there is at least a warning...

**Comment by claudiug** [comment] 2016-07-15 20:33
:shadow pseudo-element is deprecated. See /Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:26 ::shadow pseudo-https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by claudiug** [comment] 2016-07-15 20:36
is this the line that try to fetch suggestion?
https://github.com/LaurentTreguier/autocomplete-dcd/blob/master/lib/dcd-provider.coffee#L129

**Comment by LaurentTreguier** [comment] 2016-07-15 20:38
Yes it is.
I have a doubt : can you try to go to `~/.atom/packages/autocomplete-dcd/lib` and change line 178 of `dcd-provider.coffee` from `client.stdin.end(text, "ascii")` to `client.stdin.end(text, "utf8")` ? I changed this to fix a bug in the last version but maybe it broke something on OS X ?

**Comment by claudiug** [comment] 2016-07-15 20:42
change it.
kill dcd-server
kill atom
start atom
kill dcd-server (as will load all the .dub)
start dcd-server
open atom console (no result)
result from dcd-server
`2016-07-15T22:41:05.676:first.d:visit:304 Could not locate object.d or object.di
2016-07-15T22:41:05.676:first.d:visit:382 Could not resolve location of module 'std/stdio'
2016-07-15T22:41:05.676:autocomplete.d:getSymbolsByTokenChain:744 Could not find declaration of writeln from position 71
2016-07-15T22:41:05.676:server.d:main:321 Request processed in 0.339521 milliseconds
2016-07-15T22:41:05.962:server.d:main:283 Getting completions
2016-07-15T22:41:05.962:first.d:visit:304 Could not locate object.d or object.di
2016-07-15T22:41:05.963:first.d:visit:382 Could not resolve location of module 'std/stdio'
2016-07-15T22:41:05.963:autocomplete.d:getSymbolsByTokenChain:744 Could not find declaration of std from position 72
2016-07-15T22:41:05.963:server.d:main:321 Request processed in 0.310612 milliseconds
2016-07-15T22:41:06.236:server.d:main:283 Getting completions
2016-07-15T22:41:06.236:first.d:visit:304 Could not locate object.d or object.di
2016-07-15T22:41:06.236:first.d:visit:382 Could not resolve location of module 'std/stdio'
2016-07-15T22:41:06.236:autocomplete.d:getSymbolsByTokenChain:744 Could not find declaration of std from position 72
2016-07-15T22:41:06.237:server.d:main:321 Request processed in 0.371381 milliseconds
`

**Comment by claudiug** [comment] 2016-07-15 20:42
maybe this one: `Could not resolve location of module 'std/stdio'`

**Comment by LaurentTreguier** [comment] 2016-07-15 20:43
Oh, right ! Do you have a `/etc/dcd.conf` file ?

**Comment by claudiug** [comment] 2016-07-15 20:47
Have no idea. Install using brew install dcd :)

let me search

**Comment by claudiug** [comment] 2016-07-15 20:50
`sudo find / -name dcd.conf 

find: /dev/fd/3: Not a directory

find: /dev/fd/4: Not a directory`

zero result

**Comment by LaurentTreguier** [comment] 2016-07-15 20:56
No result then ? That's where the problem is... It should work if you create `~/.config/dcd/dcd.conf` (as seen [here](https://github.com/Hackerpilot/DCD#configuration-files) with the path to the standard library inside it. For me it's `/usr/include/dlang/dmd`, but it may be different on OS X. If you have a `/etc/dmd.conf` file it should be written inside

**Comment by claudiug** [comment] 2016-07-15 21:08
<img width="1280" alt="screen shot 2016-07-15 at 11 08 04 pm" src="https://cloud.githubusercontent.com/assets/969118/16888548/03ec4494-4ae1-11e6-84d8-6c3ec5dfa9c9.png">

`/Library/D/dmd

/Library/D/dmd/src/phobos

/Library/D/dmd/src/phobos/std
`

**Comment by LaurentTreguier** [comment] 2016-07-15 21:09
So I guess it's working properly now ?

**Comment by claudiug** [comment] 2016-07-15 21:11
only if I kill dcd-server after I start atom, and start it normally. otherwise cpu goes ballistic :)

**Comment by claudiug** [comment] 2016-07-15 21:12
I guess best will be to remove all the autocomplete, just start the dcd-server and tell people to add they own libraries :)

**Comment by LaurentTreguier** [comment] 2016-07-15 21:15
Maybe. I didn't intend to develop this extension any further since I don't use Atom anymore, but when I get the time, maybe I will try to get library paths from dub.selections.json. This would automatically load only the necessary libraries in dub projects.

**Comment by claudiug** [comment] 2016-07-15 21:18
that will be super good adagio. 

what are you using now. vscode? That one also is not working on mac os :)

**Comment by LaurentTreguier** [comment] 2016-07-15 21:19
"That one" ? Do you mean the editor or one of the D extensions ?

**Comment by claudiug** [comment] 2016-07-15 21:21
visual studio code, and plugin code-d dont work in mac. 
so for now, please add your plugin to dlang org, as I guess is working properly :)
https://github.com/Pure-D/code-d/issues/29

**Comment by LaurentTreguier** [comment] 2016-07-15 21:25
code-d needs its backend, [workspace-d](https://github.com/Pure-D/workspace-d), to be installed. However now I'm working on the other VSCode D extension, which doesn't require it ;-)
Anyway, I'll close this issue now that we know where the problem comes from

**Closed as completed by LaurentTreguier** 2016-07-15 21:25 UTC
